# Generated by Django 5.1 on 2024-08-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_remove_nota_actualizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='descripcion',
            new_name='contenido',
        ),
    ]
