# Generated by Django 5.1 on 2024-08-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_rename_descripcion_nota_contenido'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nota',
            table='blog',
        ),
    ]
