# Generated by Django 5.1 on 2024-08-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alter_nota_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nota',
            table=None,
        ),
    ]
